spring.application.name=skill14

spring.datasource.url=jdbc:mysql://localhost:3306/skill
spring.datasource.username=root
spring.datasource.password=Raj17511800x

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true